#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatures

runApplication blockMesh
runApplication decomposePar
runParallel snappyHexMesh -overwrite

for PROC in processor* ; do cp -rfv 0 $PROC ; done

runParallel $(getApplication)

#------------------------------------------------------------------------------
